
//! Autogenerated weights for `election_vote`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-step9-votes.jAInN4B8Nj")`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --chain=/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-step9-votes.jAInN4B8Nj
// --genesis-builder=spec-genesis
// --pallet=election_vote
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=/Users/rhett/GMB/citizenchain/scripts/benchmark-weight-template.hbs
// --output=runtime/votingengine/election-vote/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `election_vote`.
pub trait WeightInfo {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::CidByWalletAccount` (r:1 w:0)
	/// Proof: `CitizenIdentity::CidByWalletAccount` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::WalletAccountByCid` (r:1 w:0)
	/// Proof: `CitizenIdentity::WalletAccountByCid` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::PopularElectionVotesByCid` (r:1 w:1)
	/// Proof: `ElectionVote::PopularElectionVotesByCid` (`max_values`: None, `max_size`: Some(203), added: 2678, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_popular_vote(c: u32, ) -> Weight;
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::MutualElectionVotesByTicket` (r:1 w:1)
	/// Proof: `ElectionVote::MutualElectionVotesByTicket` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_mutual_vote(c: u32, ) -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::CidByWalletAccount` (r:1 w:0)
	/// Proof: `CitizenIdentity::CidByWalletAccount` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::WalletAccountByCid` (r:1 w:0)
	/// Proof: `CitizenIdentity::WalletAccountByCid` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::PopularElectionVotesByCid` (r:1 w:1)
	/// Proof: `ElectionVote::PopularElectionVotesByCid` (`max_values`: None, `max_size`: Some(203), added: 2678, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_popular_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2946 + c * (71 +/-0)`
		//  Estimated: `20131 + c * (2584 +/-0)`
		// Minimum execution time: 60_000_000 picoseconds.
		Weight::from_parts(56_315_593, 0)
			.saturating_add(Weight::from_parts(0, 20131))
			// Standard Error: 4_588
			.saturating_add(Weight::from_parts(2_257_197, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(10))
			.saturating_add(Weight::from_parts(0, 2584).saturating_mul(c.into()))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::MutualElectionVotesByTicket` (r:1 w:1)
	/// Proof: `ElectionVote::MutualElectionVotesByTicket` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_mutual_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `622 + c * (65 +/-0)`
		//  Estimated: `67255 + c * (2584 +/-0)`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(43_801_339, 0)
			.saturating_add(Weight::from_parts(0, 67255))
			// Standard Error: 4_261
			.saturating_add(Weight::from_parts(2_221_861, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(9))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(10))
			.saturating_add(Weight::from_parts(0, 2584).saturating_mul(c.into()))
	}
}

impl WeightInfo for () {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::CidByWalletAccount` (r:1 w:0)
	/// Proof: `CitizenIdentity::CidByWalletAccount` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::WalletAccountByCid` (r:1 w:0)
	/// Proof: `CitizenIdentity::WalletAccountByCid` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::PopularElectionVotesByCid` (r:1 w:1)
	/// Proof: `ElectionVote::PopularElectionVotesByCid` (`max_values`: None, `max_size`: Some(203), added: 2678, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_popular_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2946 + c * (71 +/-0)`
		//  Estimated: `20131 + c * (2584 +/-0)`
		// Minimum execution time: 60_000_000 picoseconds.
		Weight::from_parts(56_315_593, 0)
			.saturating_add(Weight::from_parts(0, 20131))
			// Standard Error: 4_588
			.saturating_add(Weight::from_parts(2_257_197, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(12))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(10))
			.saturating_add(Weight::from_parts(0, 2584).saturating_mul(c.into()))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(16666), added: 19141, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(187), added: 2662, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::VoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::VoterSnapshot` (`max_values`: None, `max_size`: Some(63790), added: 66265, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::MutualElectionVotesByTicket` (r:1 w:1)
	/// Proof: `ElectionVote::MutualElectionVotesByTicket` (`max_values`: None, `max_size`: Some(236), added: 2711, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(109), added: 2584, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InstitutionTicketCountSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::InstitutionTicketCountSnapshot` (`max_values`: None, `max_size`: Some(77), added: 2552, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(18202), added: 20677, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_mutual_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `622 + c * (65 +/-0)`
		//  Estimated: `67255 + c * (2584 +/-0)`
		// Minimum execution time: 47_000_000 picoseconds.
		Weight::from_parts(43_801_339, 0)
			.saturating_add(Weight::from_parts(0, 67255))
			// Standard Error: 4_261
			.saturating_add(Weight::from_parts(2_221_861, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(9))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(10))
			.saturating_add(Weight::from_parts(0, 2584).saturating_mul(c.into()))
	}
}
