
//! Autogenerated weights for `election_vote`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --runtime=target/release/wbuild/citizenchain/citizenchain.compact.compressed.wasm
// --genesis-builder=spec-genesis
// --pallet=election_vote
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=scripts/benchmark-weight-template.hbs
// --output=runtime/votingengine/election-vote/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `election_vote`.
pub trait WeightInfo {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionVotesByVoter` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionVotesByVoter` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshotIds` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshotIds` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::PopulationSnapshots` (r:1 w:0)
	/// Proof: `CitizenIdentity::PopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(8218), added: 10693, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(9754), added: 12229, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_popular_vote(c: u32, ) -> Weight;
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionVotesByVoter` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionVotesByVoter` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::MutualVoters` (r:1 w:0)
	/// Proof: `ElectionVote::MutualVoters` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(8218), added: 10693, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(9754), added: 12229, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_mutual_vote(c: u32, ) -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionVotesByVoter` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionVotesByVoter` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshotIds` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshotIds` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::PopulationSnapshots` (r:1 w:0)
	/// Proof: `CitizenIdentity::PopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(8218), added: 10693, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(9754), added: 12229, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_popular_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `833 + c * (32 +/-0)`
		//  Estimated: `11996 + c * (2551 +/-0)`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(47_154_910, 0)
			.saturating_add(Weight::from_parts(0, 11996))
			// Standard Error: 1_578
			.saturating_add(Weight::from_parts(1_580_324, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(9))
			.saturating_add(Weight::from_parts(0, 2551).saturating_mul(c.into()))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionVotesByVoter` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionVotesByVoter` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::MutualVoters` (r:1 w:0)
	/// Proof: `ElectionVote::MutualVoters` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(8218), added: 10693, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(9754), added: 12229, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_mutual_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503 + c * (32 +/-0)`
		//  Estimated: `11996 + c * (2551 +/-0)`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(38_212_376, 0)
			.saturating_add(Weight::from_parts(0, 11996))
			// Standard Error: 1_071
			.saturating_add(Weight::from_parts(1_566_471, 0).saturating_mul(c.into()))
			.saturating_add(T::DbWeight::get().reads(7))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(T::DbWeight::get().writes(9))
			.saturating_add(Weight::from_parts(0, 2551).saturating_mul(c.into()))
	}
}

impl WeightInfo for () {
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionVotesByVoter` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionVotesByVoter` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshotIds` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshotIds` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::PopulationSnapshots` (r:1 w:0)
	/// Proof: `CitizenIdentity::PopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(8218), added: 10693, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(9754), added: 12229, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_popular_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `833 + c * (32 +/-0)`
		//  Estimated: `11996 + c * (2551 +/-0)`
		// Minimum execution time: 48_000_000 picoseconds.
		Weight::from_parts(47_154_910, 0)
			.saturating_add(Weight::from_parts(0, 11996))
			// Standard Error: 1_578
			.saturating_add(Weight::from_parts(1_580_324, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(10))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(9))
			.saturating_add(Weight::from_parts(0, 2551).saturating_mul(c.into()))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionVotesByVoter` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionVotesByVoter` (`max_values`: None, `max_size`: Some(104), added: 2579, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::MutualVoters` (r:1 w:0)
	/// Proof: `ElectionVote::MutualVoters` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidates` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionCandidates` (`max_values`: None, `max_size`: Some(8218), added: 10693, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionCandidateTallies` (r:256 w:1)
	/// Proof: `ElectionVote::ElectionCandidateTallies` (`max_values`: None, `max_size`: Some(76), added: 2551, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionTallyStore` (r:1 w:1)
	/// Proof: `ElectionVote::ElectionTallyStore` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionMetaStore` (r:1 w:0)
	/// Proof: `ElectionVote::ElectionMetaStore` (`max_values`: None, `max_size`: Some(230), added: 2705, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `ElectionVote::ElectionResults` (r:0 w:1)
	/// Proof: `ElectionVote::ElectionResults` (`max_values`: None, `max_size`: Some(9754), added: 12229, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// The range of component `c` is `[1, 256]`.
	fn cast_mutual_vote(c: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `503 + c * (32 +/-0)`
		//  Estimated: `11996 + c * (2551 +/-0)`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(38_212_376, 0)
			.saturating_add(Weight::from_parts(0, 11996))
			// Standard Error: 1_071
			.saturating_add(Weight::from_parts(1_566_471, 0).saturating_mul(c.into()))
			.saturating_add(RocksDbWeight::get().reads(7))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(c.into())))
			.saturating_add(RocksDbWeight::get().writes(9))
			.saturating_add(Weight::from_parts(0, 2551).saturating_mul(c.into()))
	}
}
