
//! Autogenerated weights for `duoqian_transaction_pow`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm46oaq`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /home/runner/work/GMB/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// duoqian_transaction_pow
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /home/runner/work/GMB/GMB/citizenchain/transaction/duoqian-transaction-pow/src/weights.rs
// --template
// /home/runner/work/GMB/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `duoqian_transaction_pow`.
pub trait WeightInfo {
	fn register_sfid_institution() -> Weight;
	fn create_duoqian(a: u32, s: u32, ) -> Weight;
	fn close_duoqian(a: u32, s: u32, ) -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `DuoqianTransactionPow::ChainDomainHash` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::ChainDomainHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidMainAccount` (r:1 w:0)
	/// Proof: `SfidCodeAuth::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::SfidRegisteredAddress` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::SfidRegisteredAddress` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::AddressRegisteredSfid` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::AddressRegisteredSfid` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	fn register_sfid_institution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225`
		//  Estimated: `3619`
		// Minimum execution time: 50_033_000 picoseconds.
		Weight::from_parts(51_215_000, 0)
			.saturating_add(Weight::from_parts(0, 3619))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `DuoqianTransactionPow::SfidRegisteredAddress` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::SfidRegisteredAddress` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::AddressRegisteredSfid` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::AddressRegisteredSfid` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::DuoqianAccounts` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::DuoqianAccounts` (`max_values`: None, `max_size`: Some(2142), added: 4617, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::ChainDomainHash` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::ChainDomainHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[2, 64]`.
	/// The range of component `s` is `[2, 64]`.
	fn create_duoqian(_a: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `703`
		//  Estimated: `6196`
		// Minimum execution time: 2_543_882_000 picoseconds.
		Weight::from_parts(2_358_807_031, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			// Standard Error: 432_656
			.saturating_add(Weight::from_parts(34_533_713, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `DuoqianTransactionPow::DuoqianAccounts` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::DuoqianAccounts` (`max_values`: None, `max_size`: Some(2142), added: 4617, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::ChainDomainHash` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::ChainDomainHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::AddressRegisteredSfid` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::AddressRegisteredSfid` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[2, 64]`.
	/// The range of component `s` is `[2, 64]`.
	fn close_duoqian(_a: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2693`
		//  Estimated: `6196`
		// Minimum execution time: 2_087_752_000 picoseconds.
		Weight::from_parts(1_819_664_459, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			// Standard Error: 444_236
			.saturating_add(Weight::from_parts(36_706_717, 0).saturating_mul(s.into()))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(4))
	}
}

impl WeightInfo for () {
	/// Storage: `DuoqianTransactionPow::ChainDomainHash` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::ChainDomainHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidMainAccount` (r:1 w:0)
	/// Proof: `SfidCodeAuth::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::SfidRegisteredAddress` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::SfidRegisteredAddress` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::AddressRegisteredSfid` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::AddressRegisteredSfid` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	fn register_sfid_institution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225`
		//  Estimated: `3619`
		// Minimum execution time: 50_033_000 picoseconds.
		Weight::from_parts(51_215_000, 0)
			.saturating_add(Weight::from_parts(0, 3619))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	/// Storage: `DuoqianTransactionPow::SfidRegisteredAddress` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::SfidRegisteredAddress` (`max_values`: None, `max_size`: Some(146), added: 2621, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::AddressRegisteredSfid` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::AddressRegisteredSfid` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::DuoqianAccounts` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::DuoqianAccounts` (`max_values`: None, `max_size`: Some(2142), added: 4617, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::ChainDomainHash` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::ChainDomainHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[2, 64]`.
	/// The range of component `s` is `[2, 64]`.
	fn create_duoqian(_a: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `703`
		//  Estimated: `6196`
		// Minimum execution time: 2_543_882_000 picoseconds.
		Weight::from_parts(2_358_807_031, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			// Standard Error: 432_656
			.saturating_add(Weight::from_parts(34_533_713, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: `DuoqianTransactionPow::DuoqianAccounts` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::DuoqianAccounts` (`max_values`: None, `max_size`: Some(2142), added: 4617, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:2 w:2)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::ChainDomainHash` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::ChainDomainHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `DuoqianTransactionPow::AddressRegisteredSfid` (r:1 w:1)
	/// Proof: `DuoqianTransactionPow::AddressRegisteredSfid` (`max_values`: None, `max_size`: Some(154), added: 2629, mode: `MaxEncodedLen`)
	/// The range of component `a` is `[2, 64]`.
	/// The range of component `s` is `[2, 64]`.
	fn close_duoqian(_a: u32, s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2693`
		//  Estimated: `6196`
		// Minimum execution time: 2_087_752_000 picoseconds.
		Weight::from_parts(1_819_664_459, 0)
			.saturating_add(Weight::from_parts(0, 6196))
			// Standard Error: 444_236
			.saturating_add(Weight::from_parts(36_706_717, 0).saturating_mul(s.into()))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
}
