
//! Autogenerated weights for `duoqian_transaction_pow`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /Users/rhett/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// duoqian_transaction_pow
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /Users/rhett/GMB/citizenchain/transaction/duoqian-transaction-pow/src/weights.rs
// --template
// /Users/rhett/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `duoqian_transaction_pow`.
pub trait WeightInfo {
	fn register_sfid_institution() -> Weight;
	fn create_duoqian(admin_count: u32, approval_count: u32) -> Weight;
	fn close_duoqian(admin_count: u32, approval_count: u32) -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `DuoqianTransactionPow::ChainDomainHash` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::ChainDomainHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn register_sfid_institution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `98`
		//  Estimated: `1517`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1517))
			.saturating_add(T::DbWeight::get().reads(1))
	}
	fn create_duoqian(admin_count: u32, approval_count: u32) -> Weight {
		Weight::from_parts(120_000_000, 4_096)
			.saturating_add(Weight::from_parts(8_000_000, 128).saturating_mul(admin_count as u64))
			.saturating_add(
				Weight::from_parts(25_000_000, 256).saturating_mul(approval_count as u64),
			)
	}
	fn close_duoqian(admin_count: u32, approval_count: u32) -> Weight {
		Weight::from_parts(95_000_000, 3_072)
			.saturating_add(Weight::from_parts(8_000_000, 128).saturating_mul(admin_count as u64))
			.saturating_add(
				Weight::from_parts(25_000_000, 256).saturating_mul(approval_count as u64),
			)
	}
}

impl WeightInfo for () {
	/// Storage: `DuoqianTransactionPow::ChainDomainHash` (r:1 w:0)
	/// Proof: `DuoqianTransactionPow::ChainDomainHash` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn register_sfid_institution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `98`
		//  Estimated: `1517`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(4_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1517))
			.saturating_add(RocksDbWeight::get().reads(1))
	}
	fn create_duoqian(admin_count: u32, approval_count: u32) -> Weight {
		Weight::from_parts(120_000_000, 4_096)
			.saturating_add(Weight::from_parts(8_000_000, 128).saturating_mul(admin_count as u64))
			.saturating_add(
				Weight::from_parts(25_000_000, 256).saturating_mul(approval_count as u64),
			)
	}
	fn close_duoqian(admin_count: u32, approval_count: u32) -> Weight {
		Weight::from_parts(95_000_000, 3_072)
			.saturating_add(Weight::from_parts(8_000_000, 128).saturating_mul(admin_count as u64))
			.saturating_add(
				Weight::from_parts(25_000_000, 256).saturating_mul(approval_count as u64),
			)
	}
}
