
//! Autogenerated weights for `resolution_issuance_iss`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /Users/rhett/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// resolution_issuance_iss
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /Users/rhett/GMB/citizenchain/issuance/resolution-issuance-iss/src/weights.rs
// --template
// /Users/rhett/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `resolution_issuance_iss`.
pub trait WeightInfo {
	fn execute_resolution_issuance(reason_len: u32, allocation_count: u32, ) -> Weight;
	fn clear_executed() -> Weight;
	fn set_paused() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ResolutionIssuanceIss::Paused` (r:1 w:0)
	/// Proof: `ResolutionIssuanceIss::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuanceIss::EverExecuted` (r:1 w:1)
	/// Proof: `ResolutionIssuanceIss::EverExecuted` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuanceIss::TotalIssued` (r:1 w:1)
	/// Proof: `ResolutionIssuanceIss::TotalIssued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuanceIss::Executed` (r:0 w:1)
	/// Proof: `ResolutionIssuanceIss::Executed` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// The range of component `reason_len` is `[1, 1024]`.
	/// The range of component `allocation_count` is `[1, 43]`.
	fn execute_resolution_issuance(_reason_len: u32, allocation_count: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `295 + allocation_count * (23 ±0)`
		//  Estimated: `3481 + allocation_count * (2603 ±0)`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(23_327_051, 0)
			.saturating_add(Weight::from_parts(0, 3481))
			// Standard Error: 15_425
			.saturating_add(Weight::from_parts(9_981_152, 0).saturating_mul(allocation_count.into()))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(allocation_count.into())))
			.saturating_add(T::DbWeight::get().writes(3))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(allocation_count.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(allocation_count.into()))
	}
	/// Storage: `ResolutionIssuanceIss::Executed` (r:1 w:1)
	/// Proof: `ResolutionIssuanceIss::Executed` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn clear_executed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `221`
		//  Estimated: `3485`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3485))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ResolutionIssuanceIss::Paused` (r:1 w:1)
	/// Proof: `ResolutionIssuanceIss::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1486`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1486))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	/// Storage: `ResolutionIssuanceIss::Paused` (r:1 w:0)
	/// Proof: `ResolutionIssuanceIss::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuanceIss::EverExecuted` (r:1 w:1)
	/// Proof: `ResolutionIssuanceIss::EverExecuted` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuanceIss::TotalIssued` (r:1 w:1)
	/// Proof: `ResolutionIssuanceIss::TotalIssued` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuanceIss::Executed` (r:0 w:1)
	/// Proof: `ResolutionIssuanceIss::Executed` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// The range of component `reason_len` is `[1, 1024]`.
	/// The range of component `allocation_count` is `[1, 43]`.
	fn execute_resolution_issuance(_reason_len: u32, allocation_count: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `295 + allocation_count * (23 ±0)`
		//  Estimated: `3481 + allocation_count * (2603 ±0)`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(23_327_051, 0)
			.saturating_add(Weight::from_parts(0, 3481))
			// Standard Error: 15_425
			.saturating_add(Weight::from_parts(9_981_152, 0).saturating_mul(allocation_count.into()))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(allocation_count.into())))
			.saturating_add(RocksDbWeight::get().writes(3))
			.saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(allocation_count.into())))
			.saturating_add(Weight::from_parts(0, 2603).saturating_mul(allocation_count.into()))
	}
	/// Storage: `ResolutionIssuanceIss::Executed` (r:1 w:1)
	/// Proof: `ResolutionIssuanceIss::Executed` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn clear_executed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `221`
		//  Estimated: `3485`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3485))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: `ResolutionIssuanceIss::Paused` (r:1 w:1)
	/// Proof: `ResolutionIssuanceIss::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1486`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1486))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
