
//! Autogenerated weights for `shengbank_interest`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-06-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --runtime=/Users/rhett/GMB/citizenchain/target/release/wbuild/citizenchain/citizenchain.compact.compressed.wasm
// --genesis-builder=spec-genesis
// --pallet=shengbank_interest
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=/Users/rhett/GMB/citizenchain/scripts/benchmark-weight-template.hbs
// --output=runtime/issuance/shengbank-interest/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `shengbank_interest`.
pub trait WeightInfo {
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `y` is `[1, 8]`.
	fn force_settle_years(y: u32, ) -> Weight;
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn force_advance_year() -> Weight;
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn on_initialize_settlement() -> Weight;
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:0)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn on_initialize_boundary_noop() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `y` is `[1, 8]`.
	fn force_settle_years(y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1961`
		//  Estimated: `112919`
		// Minimum execution time: 554_000_000 picoseconds.
		Weight::from_parts(201_417_460, 0)
			.saturating_add(Weight::from_parts(0, 112919))
			// Standard Error: 231_865
			.saturating_add(Weight::from_parts(364_958_465, 0).saturating_mul(y.into()))
			.saturating_add(T::DbWeight::get().reads(44))
			.saturating_add(T::DbWeight::get().writes(44))
	}
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn force_advance_year() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `1489`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn on_initialize_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1988`
		//  Estimated: `112919`
		// Minimum execution time: 544_000_000 picoseconds.
		Weight::from_parts(563_000_000, 0)
			.saturating_add(Weight::from_parts(0, 112919))
			.saturating_add(T::DbWeight::get().reads(44))
			.saturating_add(T::DbWeight::get().writes(44))
	}
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:0)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn on_initialize_boundary_noop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `1489`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
	}
}

impl WeightInfo for () {
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `y` is `[1, 8]`.
	fn force_settle_years(y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1961`
		//  Estimated: `112919`
		// Minimum execution time: 554_000_000 picoseconds.
		Weight::from_parts(201_417_460, 0)
			.saturating_add(Weight::from_parts(0, 112919))
			// Standard Error: 231_865
			.saturating_add(Weight::from_parts(364_958_465, 0).saturating_mul(y.into()))
			.saturating_add(RocksDbWeight::get().reads(44))
			.saturating_add(RocksDbWeight::get().writes(44))
	}
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn force_advance_year() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `1489`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn on_initialize_settlement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1988`
		//  Estimated: `112919`
		// Minimum execution time: 544_000_000 picoseconds.
		Weight::from_parts(563_000_000, 0)
			.saturating_add(Weight::from_parts(0, 112919))
			.saturating_add(RocksDbWeight::get().reads(44))
			.saturating_add(RocksDbWeight::get().writes(44))
	}
	/// Storage: `ShengBankInterest::LastSettledYear` (r:1 w:0)
	/// Proof: `ShengBankInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn on_initialize_boundary_noop() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `1489`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(RocksDbWeight::get().reads(1))
	}
}
