
//! Autogenerated weights for `multisig_transfer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-06-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --runtime=/Users/rhett/GMB/citizenchain/target/release/wbuild/citizenchain/citizenchain.compact.compressed.wasm
// --genesis-builder=spec-genesis
// --pallet=multisig_transfer
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=/Users/rhett/GMB/citizenchain/scripts/benchmark-weight-template.hbs
// --output=runtime/transaction/multisig-transfer/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `multisig_transfer`.
pub trait WeightInfo {
	/// Storage: `GenesisAdmins/PublicAdmins/PrivateAdmins::AdminAccounts` (r:1 w:0)
	/// Proof: `GenesisAdmins/PublicAdmins/PrivateAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(63744), added: 66219, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsByInstitution` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsByInstitution` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:1 w:1)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(9498), added: 11973, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalVotesByAccount` (r:1 w:1)
	/// Proof: `InternalVote::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalTallies` (r:1 w:1)
	/// Proof: `InternalVote::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCode` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByCode` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AdminSnapshot` (r:0 w:1)
	/// Proof: `VotingEngine::AdminSnapshot` (`max_values`: None, `max_size`: Some(63722), added: 66197, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByInstitution` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByInstitution` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalThresholdSnapshot` (r:0 w:1)
	/// Proof: `InternalVote::InternalThresholdSnapshot` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:0 w:1)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn propose_transfer() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `GenesisAdmins/PublicAdmins/PrivateAdmins::AdminAccounts` (r:1 w:0)
	/// Proof: `GenesisAdmins/PublicAdmins/PrivateAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(63744), added: 66219, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsByInstitution` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsByInstitution` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:1 w:1)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(9498), added: 11973, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalVotesByAccount` (r:1 w:1)
	/// Proof: `InternalVote::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalTallies` (r:1 w:1)
	/// Proof: `InternalVote::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCode` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByCode` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AdminSnapshot` (r:0 w:1)
	/// Proof: `VotingEngine::AdminSnapshot` (`max_values`: None, `max_size`: Some(63722), added: 66197, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByInstitution` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByInstitution` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalThresholdSnapshot` (r:0 w:1)
	/// Proof: `InternalVote::InternalThresholdSnapshot` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:0 w:1)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn propose_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1552`
		//  Estimated: `105893`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(71_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(21))
	}
}

impl WeightInfo for () {
	/// Storage: `GenesisAdmins/PublicAdmins/PrivateAdmins::AdminAccounts` (r:1 w:0)
	/// Proof: `GenesisAdmins/PublicAdmins/PrivateAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(63744), added: 66219, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:0)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsByInstitution` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsByInstitution` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:1 w:1)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(9498), added: 11973, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalVotesByAccount` (r:1 w:1)
	/// Proof: `InternalVote::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalTallies` (r:1 w:1)
	/// Proof: `InternalVote::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCode` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByCode` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AdminSnapshot` (r:0 w:1)
	/// Proof: `VotingEngine::AdminSnapshot` (`max_values`: None, `max_size`: Some(63722), added: 66197, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByInstitution` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByInstitution` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalThresholdSnapshot` (r:0 w:1)
	/// Proof: `InternalVote::InternalThresholdSnapshot` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `InternalVote::InternalProposalRoles` (r:0 w:1)
	/// Proof: `InternalVote::InternalProposalRoles` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn propose_transfer() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1552`
		//  Estimated: `105893`
		// Minimum execution time: 69_000_000 picoseconds.
		Weight::from_parts(71_000_000, 0)
			.saturating_add(Weight::from_parts(0, 105893))
			.saturating_add(RocksDbWeight::get().reads(13))
			.saturating_add(RocksDbWeight::get().writes(21))
	}
}
