//!  联邦立法院机构常量=china_lf.rs

pub const CHINA_LF: &[ChinaLf] = &[
    ChinaLf {
        shenfen_id: "GFR-LN001-CB0T-178132059-20260221",
        shenfen_name: "国家立法院",
        duoqian_address: hex!("191ef776e0575afa0b3a7bb33b3b3b5cf8c591c0b4deb7d091f17d16dc0f7cc9"),
        duoqian_admins: &[
            hex!(""), hex!(""), hex!(""), hex!(""), hex!(""),
        ],
    },
    ChinaLf {
        shenfen_id: "GFR-ZS001-CB08-866047042-20260221",
        shenfen_name: "中枢省立法院",
        duoqian_address: hex!("f43544661993692f9080194731dab65ef366d5398615cc2a897edadfbbe0828a"),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SLNSF000",
        shenfen_name: "岭南省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SGDSF000",
        shenfen_name: "广东省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SGXSF000",
        shenfen_name: "广西省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SFJSF000",
        shenfen_name: "福建省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SHNSF000",
        shenfen_name: "海南省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SYNSF000",
        shenfen_name: "云南省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SGZSF000",
        shenfen_name: "贵州省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SHUSF000",
        shenfen_name: "湖南省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SJXSF000",
        shenfen_name: "江西省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SZJSF000",
        shenfen_name: "浙江省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SJSSF000",
        shenfen_name: "江苏省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SSDSF000",
        shenfen_name: "山东省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SSXSF000",
        shenfen_name: "山西省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SHESF000",
        shenfen_name: "河南省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SHBSF000",
        shenfen_name: "河北省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SHISF000",
        shenfen_name: "湖北省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SSISF000",
        shenfen_name: "陕西省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SCQSF000",
        shenfen_name: "重庆省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SSCSF000",
        shenfen_name: "四川省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SGSSF000",
        shenfen_name: "甘肃省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SBPSF000",
        shenfen_name: "北平省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SHASF000",
        shenfen_name: "海滨省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SSJSF000",
        shenfen_name: "松江省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SLJSF000",
        shenfen_name: "龙江省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SJLSF000",
        shenfen_name: "吉林省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SLISF000",
        shenfen_name: "辽宁省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SNXSF000",
        shenfen_name: "宁夏省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SQHSF000",
        shenfen_name: "青海省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SAHSF000",
        shenfen_name: "安徽省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "STWSF000",
        shenfen_name: "台湾省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SXZSF000",
        shenfen_name: "西藏省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SXJSF000",
        shenfen_name: "新疆省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SXKSF000",
        shenfen_name: "西康省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SALSF000",
        shenfen_name: "阿里省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SCLSF000",
        shenfen_name: "葱岭省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "STSSF000",
        shenfen_name: "天山省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SHXSF000",
        shenfen_name: "河西省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SKLSF000",
        shenfen_name: "昆仑省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SHTSF000",
        shenfen_name: "河套省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SRHSF000",
        shenfen_name: "热河省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SXASF000",
        shenfen_name: "兴安省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
    ChinaLf {
        shenfen_id: "SHJSF000",
        shenfen_name: "合江省立法院",
        duoqian_address: hex!(""),
        duoqian_admins: &[hex!(""), hex!(""), hex!(""), hex!(""), hex!("")],
    },
];
