
//! Autogenerated weights for `fullnode_pow_reward`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm0kj6c`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /home/runner/work/GMB/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// fullnode_pow_reward
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /home/runner/work/GMB/GMB/citizenchain/issuance/fullnode-pow-reward/src/weights.rs
// --template
// /home/runner/work/GMB/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `fullnode_pow_reward`.
pub trait WeightInfo {
	fn bind_reward_wallet() -> Weight;
	fn rebind_reward_wallet() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `FullnodePowReward::RewardWalletByMiner` (r:1 w:1)
	/// Proof: `FullnodePowReward::RewardWalletByMiner` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn bind_reward_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3545`
		// Minimum execution time: 16_971_000 picoseconds.
		Weight::from_parts(17_733_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `FullnodePowReward::RewardWalletByMiner` (r:1 w:1)
	/// Proof: `FullnodePowReward::RewardWalletByMiner` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn rebind_reward_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215`
		//  Estimated: `3545`
		// Minimum execution time: 18_654_000 picoseconds.
		Weight::from_parts(19_196_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	/// Storage: `FullnodePowReward::RewardWalletByMiner` (r:1 w:1)
	/// Proof: `FullnodePowReward::RewardWalletByMiner` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn bind_reward_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `3545`
		// Minimum execution time: 16_971_000 picoseconds.
		Weight::from_parts(17_733_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: `FullnodePowReward::RewardWalletByMiner` (r:1 w:1)
	/// Proof: `FullnodePowReward::RewardWalletByMiner` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn rebind_reward_wallet() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215`
		//  Estimated: `3545`
		// Minimum execution time: 18_654_000 picoseconds.
		Weight::from_parts(19_196_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
