
//! Autogenerated weights for `voting_engine_system`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm46oaq`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /home/runner/work/GMB/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// voting_engine_system
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /home/runner/work/GMB/GMB/citizenchain/runtime/governance/voting-engine-system/src/weights.rs
// --template
// /home/runner/work/GMB/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `voting_engine_system`.
pub trait WeightInfo {
	fn create_internal_proposal() -> Weight;
	fn submit_joint_institution_vote() -> Weight;
	fn citizen_vote() -> Weight;
	fn finalize_proposal_internal() -> Weight;
	fn finalize_proposal_joint() -> Weight;
	fn finalize_proposal_citizen() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `VotingEngineSystem::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngineSystem::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn create_internal_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `74`
		//  Estimated: `1493`
		// Minimum execution time: 7_554_000 picoseconds.
		Weight::from_parts(7_955_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:0)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::JointVotesByInstitution` (r:1 w:1)
	/// Proof: `VotingEngineSystem::JointVotesByInstitution` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::JointTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn submit_joint_institution_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `113`
		//  Estimated: `3559`
		// Minimum execution time: 22_441_000 picoseconds.
		Weight::from_parts(23_123_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:0)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidToAccount` (r:1 w:0)
	/// Proof: `SfidCodeAuth::SfidToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::CitizenVotesBySfid` (r:1 w:1)
	/// Proof: `VotingEngineSystem::CitizenVotesBySfid` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::UsedVoteNonce` (r:1 w:1)
	/// Proof: `SfidCodeAuth::UsedVoteNonce` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::CitizenTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::CitizenTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn citizen_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `3570`
		// Minimum execution time: 37_310_000 picoseconds.
		Weight::from_parts(38_031_000, 0)
			.saturating_add(Weight::from_parts(0, 3570))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn finalize_proposal_internal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `164`
		//  Estimated: `3559`
		// Minimum execution time: 16_250_000 picoseconds.
		Weight::from_parts(16_791_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `VotingEngineSystem::JointTallies` (r:1 w:0)
	/// Proof: `VotingEngineSystem::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngineSystem::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	fn finalize_proposal_joint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `19871`
		// Minimum execution time: 24_766_000 picoseconds.
		Weight::from_parts(25_597_000, 0)
			.saturating_add(Weight::from_parts(0, 19871))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `VotingEngineSystem::CitizenTallies` (r:1 w:0)
	/// Proof: `VotingEngineSystem::CitizenTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn finalize_proposal_citizen() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `174`
		//  Estimated: `3559`
		// Minimum execution time: 19_747_000 picoseconds.
		Weight::from_parts(20_678_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	/// Storage: `VotingEngineSystem::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngineSystem::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn create_internal_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `74`
		//  Estimated: `1493`
		// Minimum execution time: 7_554_000 picoseconds.
		Weight::from_parts(7_955_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:0)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::JointVotesByInstitution` (r:1 w:1)
	/// Proof: `VotingEngineSystem::JointVotesByInstitution` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::JointTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn submit_joint_institution_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `113`
		//  Estimated: `3559`
		// Minimum execution time: 22_441_000 picoseconds.
		Weight::from_parts(23_123_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:0)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidToAccount` (r:1 w:0)
	/// Proof: `SfidCodeAuth::SfidToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::CitizenVotesBySfid` (r:1 w:1)
	/// Proof: `VotingEngineSystem::CitizenVotesBySfid` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::UsedVoteNonce` (r:1 w:1)
	/// Proof: `SfidCodeAuth::UsedVoteNonce` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::CitizenTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::CitizenTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	fn citizen_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `320`
		//  Estimated: `3570`
		// Minimum execution time: 37_310_000 picoseconds.
		Weight::from_parts(38_031_000, 0)
			.saturating_add(Weight::from_parts(0, 3570))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn finalize_proposal_internal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `164`
		//  Estimated: `3559`
		// Minimum execution time: 16_250_000 picoseconds.
		Weight::from_parts(16_791_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: `VotingEngineSystem::JointTallies` (r:1 w:0)
	/// Proof: `VotingEngineSystem::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngineSystem::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	fn finalize_proposal_joint() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `169`
		//  Estimated: `19871`
		// Minimum execution time: 24_766_000 picoseconds.
		Weight::from_parts(25_597_000, 0)
			.saturating_add(Weight::from_parts(0, 19871))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(2))
	}
	/// Storage: `VotingEngineSystem::CitizenTallies` (r:1 w:0)
	/// Proof: `VotingEngineSystem::CitizenTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn finalize_proposal_citizen() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `174`
		//  Estimated: `3559`
		// Minimum execution time: 19_747_000 picoseconds.
		Weight::from_parts(20_678_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
