
//! Autogenerated weights for `admins_change`
//!
//! 注意：本文件在旧代码（含 ProposalActions/ActiveProposalByInstitution/ProposalCreatedAt/ProposalPassedAt）
//! 上生成，当前代码已移除这些存储项（业务数据改存投票引擎 ProposalData）。
//! 权重数值是旧代码的过估（安全但不精确），storage proof 注释不再反映实际读写路径。
//! 须在代码稳定后重新运行 benchmark。
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm46oaq`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("citizenchain")`, DB CACHE: 1024

// Executed Command:
// /home/runner/work/GMB/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// citizenchain
// --pallet
// admins_change
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /home/runner/work/GMB/GMB/citizenchain/runtime/governance/admins-change/src/weights.rs
// --template
// /home/runner/work/GMB/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `admins_change`.
pub trait WeightInfo {
	fn propose_admin_replacement() -> Weight;
	fn execute_admin_replacement() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AdminsChange::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsChange::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalActions` (r:1 w:2)
	/// Proof: `AdminsChange::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:2)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::Institutions` (r:1 w:0)
	/// Proof: `AdminsChange::Institutions` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalPassedAt` (r:0 w:1)
	/// Proof: `AdminsChange::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalCreatedAt` (r:0 w:2)
	/// Proof: `AdminsChange::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngine::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn propose_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1551`
		//  Estimated: `19871`
		// Minimum execution time: 84_968_000 picoseconds.
		Weight::from_parts(87_473_000, 0)
			.saturating_add(Weight::from_parts(0, 19871))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(12))
	}
	/// Storage: `AdminsChange::ProposalActions` (r:1 w:1)
	/// Proof: `AdminsChange::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::Institutions` (r:1 w:1)
	/// Proof: `AdminsChange::Institutions` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsChange::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalPassedAt` (r:0 w:1)
	/// Proof: `AdminsChange::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `AdminsChange::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngine::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn execute_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1601`
		//  Estimated: `4554`
		// Minimum execution time: 56_615_000 picoseconds.
		Weight::from_parts(57_887_000, 0)
			.saturating_add(Weight::from_parts(0, 4554))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(8))
	}
}

impl WeightInfo for () {
	/// Storage: `AdminsChange::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsChange::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalActions` (r:1 w:2)
	/// Proof: `AdminsChange::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:2)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::Institutions` (r:1 w:0)
	/// Proof: `AdminsChange::Institutions` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalPassedAt` (r:0 w:1)
	/// Proof: `AdminsChange::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalCreatedAt` (r:0 w:2)
	/// Proof: `AdminsChange::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngine::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn propose_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1551`
		//  Estimated: `19871`
		// Minimum execution time: 84_968_000 picoseconds.
		Weight::from_parts(87_473_000, 0)
			.saturating_add(Weight::from_parts(0, 19871))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(12))
	}
	/// Storage: `AdminsChange::ProposalActions` (r:1 w:1)
	/// Proof: `AdminsChange::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::Institutions` (r:1 w:1)
	/// Proof: `AdminsChange::Institutions` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsChange::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalPassedAt` (r:0 w:1)
	/// Proof: `AdminsChange::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `AdminsChange::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `AdminsChange::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngine::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn execute_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1601`
		//  Estimated: `4554`
		// Minimum execution time: 56_615_000 picoseconds.
		Weight::from_parts(57_887_000, 0)
			.saturating_add(Weight::from_parts(0, 4554))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
}
