
//! Autogenerated weights for `admins_origin_gov`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /Users/rhett/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// admins_origin_gov
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /Users/rhett/GMB/citizenchain/governance/admins-origin-gov/src/weights.rs
// --template
// /Users/rhett/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `admins_origin_gov`.
pub trait WeightInfo {
	fn propose_admin_replacement() -> Weight;
	fn vote_admin_replacement() -> Weight;
	fn execute_admin_replacement() -> Weight;
	fn cancel_stale_proposal() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `AdminsOriginGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngineSystem::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngineSystem::ProposalsByExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AdminsOriginGov::ProposalActions` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn propose_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1067`
		//  Estimated: `4554`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(19_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4554))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `AdminsOriginGov::ProposalActions` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:1)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:6 w:6)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalPassedAt` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn vote_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1907`
		//  Estimated: `16278`
		// Minimum execution time: 46_000_000 picoseconds.
		Weight::from_parts(48_000_000, 0)
			.saturating_add(Weight::from_parts(0, 16278))
			.saturating_add(T::DbWeight::get().reads(12))
			.saturating_add(T::DbWeight::get().writes(13))
	}
	/// Storage: `AdminsOriginGov::ProposalActions` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:1)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:6 w:6)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn execute_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1907`
		//  Estimated: `16278`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_000_000, 0)
			.saturating_add(Weight::from_parts(0, 16278))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(13))
	}
	/// Storage: `AdminsOriginGov::ProposalActions` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalCreatedAt` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn cancel_stale_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `558`
		//  Estimated: `3594`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3594))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(6))
	}
}

impl WeightInfo for () {
	/// Storage: `AdminsOriginGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngineSystem::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngineSystem::ProposalsByExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `AdminsOriginGov::ProposalActions` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	fn propose_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1067`
		//  Estimated: `4554`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(19_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4554))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
	/// Storage: `AdminsOriginGov::ProposalActions` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:1)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:6 w:6)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalPassedAt` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn vote_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1907`
		//  Estimated: `16278`
		// Minimum execution time: 46_000_000 picoseconds.
		Weight::from_parts(48_000_000, 0)
			.saturating_add(Weight::from_parts(0, 16278))
			.saturating_add(RocksDbWeight::get().reads(12))
			.saturating_add(RocksDbWeight::get().writes(13))
	}
	/// Storage: `AdminsOriginGov::ProposalActions` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:1)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:6 w:6)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn execute_admin_replacement() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1907`
		//  Estimated: `16278`
		// Minimum execution time: 27_000_000 picoseconds.
		Weight::from_parts(28_000_000, 0)
			.saturating_add(Weight::from_parts(0, 16278))
			.saturating_add(RocksDbWeight::get().reads(10))
			.saturating_add(RocksDbWeight::get().writes(13))
	}
	/// Storage: `AdminsOriginGov::ProposalActions` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalActions` (`max_values`: None, `max_size`: Some(129), added: 2604, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalCreatedAt` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `AdminsOriginGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `AdminsOriginGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn cancel_stale_proposal() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `558`
		//  Estimated: `3594`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3594))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
}
