
//! Autogenerated weights for `resolution_issuance`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --runtime=target/release/wbuild/citizenchain/citizenchain.compact.compressed.wasm
// --genesis-builder=spec-genesis
// --pallet=resolution_issuance
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=scripts/benchmark-weight-template.hbs
// --output=runtime/issuance/resolution-issuance/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `resolution_issuance`.
pub trait WeightInfo {
	/// Storage: `ResolutionIssuance::VotingProposalCount` (r:1 w:0)
	/// Proof: `ResolutionIssuance::VotingProposalCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuance::AllowedRecipients` (r:1 w:1)
	/// Proof: `ResolutionIssuance::AllowedRecipients` (`max_values`: Some(1), `max_size`: Some(1377), added: 1872, mode: `MaxEncodedLen`)
	fn set_allowed_recipients() -> Weight;
	/// Storage: `PublicAdmins::AdminAccounts` (r:87 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(63736), added: 66211, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuance::AllowedRecipients` (r:1 w:0)
	/// Proof: `ResolutionIssuance::AllowedRecipients` (`max_values`: Some(1), `max_size`: Some(1377), added: 1872, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::PendingPopulationSnapshots` (r:1 w:1)
	/// Proof: `JointVote::PendingPopulationSnapshots` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:87 w:87)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:87 w:87)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshotIds` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalPopulationSnapshotIds` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuance::VotingProposalCount` (r:1 w:1)
	/// Proof: `ResolutionIssuance::VotingProposalCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCid` (r:0 w:87)
	/// Proof: `VotingEngine::ProposalsByCid` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AdminSnapshot` (r:0 w:87)
	/// Proof: `VotingEngine::AdminSnapshot` (`max_values`: None, `max_size`: Some(63722), added: 66197, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn propose_issuance() -> Weight;
	/// Storage: `ResolutionIssuance::Executed` (r:1 w:1)
	/// Proof: `ResolutionIssuance::Executed` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn clear_executed() -> Weight;
	/// Storage: `ResolutionIssuance::Paused` (r:1 w:1)
	/// Proof: `ResolutionIssuance::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_paused() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ResolutionIssuance::VotingProposalCount` (r:1 w:0)
	/// Proof: `ResolutionIssuance::VotingProposalCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuance::AllowedRecipients` (r:1 w:1)
	/// Proof: `ResolutionIssuance::AllowedRecipients` (`max_values`: Some(1), `max_size`: Some(1377), added: 1872, mode: `MaxEncodedLen`)
	fn set_allowed_recipients() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1469`
		//  Estimated: `2862`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2862))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `PublicAdmins::AdminAccounts` (r:87 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(63736), added: 66211, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuance::AllowedRecipients` (r:1 w:0)
	/// Proof: `ResolutionIssuance::AllowedRecipients` (`max_values`: Some(1), `max_size`: Some(1377), added: 1872, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::PendingPopulationSnapshots` (r:1 w:1)
	/// Proof: `JointVote::PendingPopulationSnapshots` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:87 w:87)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:87 w:87)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshotIds` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalPopulationSnapshotIds` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuance::VotingProposalCount` (r:1 w:1)
	/// Proof: `ResolutionIssuance::VotingProposalCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCid` (r:0 w:87)
	/// Proof: `VotingEngine::ProposalsByCid` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AdminSnapshot` (r:0 w:87)
	/// Proof: `VotingEngine::AdminSnapshot` (`max_values`: None, `max_size`: Some(63722), added: 66197, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn propose_issuance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `32748`
		//  Estimated: `5761347`
		// Minimum execution time: 1_628_000_000 picoseconds.
		Weight::from_parts(1_669_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5761347))
			.saturating_add(T::DbWeight::get().reads(272))
			.saturating_add(T::DbWeight::get().writes(363))
	}
	/// Storage: `ResolutionIssuance::Executed` (r:1 w:1)
	/// Proof: `ResolutionIssuance::Executed` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn clear_executed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3485`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3485))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	/// Storage: `ResolutionIssuance::Paused` (r:1 w:1)
	/// Proof: `ResolutionIssuance::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `1486`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1486))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	/// Storage: `ResolutionIssuance::VotingProposalCount` (r:1 w:0)
	/// Proof: `ResolutionIssuance::VotingProposalCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuance::AllowedRecipients` (r:1 w:1)
	/// Proof: `ResolutionIssuance::AllowedRecipients` (`max_values`: Some(1), `max_size`: Some(1377), added: 1872, mode: `MaxEncodedLen`)
	fn set_allowed_recipients() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1469`
		//  Estimated: `2862`
		// Minimum execution time: 13_000_000 picoseconds.
		Weight::from_parts(14_000_000, 0)
			.saturating_add(Weight::from_parts(0, 2862))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: `PublicAdmins::AdminAccounts` (r:87 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(63736), added: 66211, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuance::AllowedRecipients` (r:1 w:0)
	/// Proof: `ResolutionIssuance::AllowedRecipients` (`max_values`: Some(1), `max_size`: Some(1377), added: 1872, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::PendingPopulationSnapshots` (r:1 w:1)
	/// Proof: `JointVote::PendingPopulationSnapshots` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:87 w:87)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:87 w:87)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshotIds` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalPopulationSnapshotIds` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionIssuance::VotingProposalCount` (r:1 w:1)
	/// Proof: `ResolutionIssuance::VotingProposalCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCid` (r:0 w:87)
	/// Proof: `VotingEngine::ProposalsByCid` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AdminSnapshot` (r:0 w:87)
	/// Proof: `VotingEngine::AdminSnapshot` (`max_values`: None, `max_size`: Some(63722), added: 66197, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn propose_issuance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `32748`
		//  Estimated: `5761347`
		// Minimum execution time: 1_628_000_000 picoseconds.
		Weight::from_parts(1_669_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5761347))
			.saturating_add(RocksDbWeight::get().reads(272))
			.saturating_add(RocksDbWeight::get().writes(363))
	}
	/// Storage: `ResolutionIssuance::Executed` (r:1 w:1)
	/// Proof: `ResolutionIssuance::Executed` (`max_values`: None, `max_size`: Some(20), added: 2495, mode: `MaxEncodedLen`)
	fn clear_executed() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `187`
		//  Estimated: `3485`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3485))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
	/// Storage: `ResolutionIssuance::Paused` (r:1 w:1)
	/// Proof: `ResolutionIssuance::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn set_paused() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `80`
		//  Estimated: `1486`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1486))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
