
//! Autogenerated weights for `runtime_root_upgrade`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /Users/rhett/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// runtime_root_upgrade
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /Users/rhett/GMB/citizenchain/governance/runtime-root-upgrade/src/weights.rs
// --template
// /Users/rhett/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `runtime_root_upgrade`.
pub trait WeightInfo {
	fn propose_runtime_upgrade() -> Weight;
	fn finalize_joint_vote() -> Weight;
	fn retry_failed_execution() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `RuntimeRootUpgrade::NextProposalId` (r:1 w:1)
	/// Proof: `RuntimeRootUpgrade::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::JointVoteToGov` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::JointVoteToGov` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::GovToJointVote` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::GovToJointVote` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::Proposals` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::Proposals` (`max_values`: None, `max_size`: Some(5243999), added: 5246474, mode: `MaxEncodedLen`)
	fn propose_runtime_upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1493`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `RuntimeRootUpgrade::Proposals` (r:1 w:1)
	/// Proof: `RuntimeRootUpgrade::Proposals` (`max_values`: None, `max_size`: Some(5243999), added: 5246474, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::GovToJointVote` (r:1 w:1)
	/// Proof: `RuntimeRootUpgrade::GovToJointVote` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::JointTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::CitizenTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::CitizenTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::RetryCount` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::RetryCount` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::JointVoteToGov` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::JointVoteToGov` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn finalize_joint_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `500`
		//  Estimated: `5247464`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5247464))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(7))
	}
	/// Storage: `RuntimeRootUpgrade::RetryCount` (r:1 w:1)
	/// Proof: `RuntimeRootUpgrade::RetryCount` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn retry_failed_execution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3493`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3493))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	/// Storage: `RuntimeRootUpgrade::NextProposalId` (r:1 w:1)
	/// Proof: `RuntimeRootUpgrade::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::JointVoteToGov` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::JointVoteToGov` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::GovToJointVote` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::GovToJointVote` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::Proposals` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::Proposals` (`max_values`: None, `max_size`: Some(5243999), added: 5246474, mode: `MaxEncodedLen`)
	fn propose_runtime_upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `109`
		//  Estimated: `1493`
		// Minimum execution time: 5_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 1493))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: `RuntimeRootUpgrade::Proposals` (r:1 w:1)
	/// Proof: `RuntimeRootUpgrade::Proposals` (`max_values`: None, `max_size`: Some(5243999), added: 5246474, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::GovToJointVote` (r:1 w:1)
	/// Proof: `RuntimeRootUpgrade::GovToJointVote` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::JointTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::CitizenTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::CitizenTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::RetryCount` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::RetryCount` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `RuntimeRootUpgrade::JointVoteToGov` (r:0 w:1)
	/// Proof: `RuntimeRootUpgrade::JointVoteToGov` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn finalize_joint_vote() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `500`
		//  Estimated: `5247464`
		// Minimum execution time: 18_000_000 picoseconds.
		Weight::from_parts(19_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5247464))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(7))
	}
	/// Storage: `RuntimeRootUpgrade::RetryCount` (r:1 w:1)
	/// Proof: `RuntimeRootUpgrade::RetryCount` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn retry_failed_execution() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `196`
		//  Estimated: `3493`
		// Minimum execution time: 4_000_000 picoseconds.
		Weight::from_parts(5_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3493))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
