
//! Autogenerated weights for `sfid_system`
//!
//! 注意：本文件仍是旧实现路径上生成的 benchmark 产物。
//! 其中 proof 注释仍引用已删除的旧存储项（如 `UsedCredentialNonce`、
//! `SfidToAccount`、`AccountToSfid`、`CredentialNoncesByExpiry`），
//! 不能再被当作当前代码真实读写路径的准确说明。
//! 权重数值是旧代码的过估（安全但不精确），须在代码稳定后重新生成。
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-17, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm46oaq`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("citizenchain")`, DB CACHE: 1024

// Executed Command:
// /home/runner/work/GMB/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// citizenchain
// --pallet
// sfid_system
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /home/runner/work/GMB/GMB/citizenchain/runtime/otherpallet/sfid-system/src/weights.rs
// --template
// /home/runner/work/GMB/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `sfid_system`.
pub trait WeightInfo {
	fn bind_sfid() -> Weight;
	fn unbind_sfid() -> Weight;
	fn rotate_sfid_keys() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SfidSystem::UsedCredentialNonce` (r:1 w:1)
	/// Proof: `SfidSystem::UsedCredentialNonce` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::SfidMainAccount` (r:1 w:0)
	/// Proof: `SfidSystem::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::SfidToAccount` (r:1 w:1)
	/// Proof: `SfidSystem::SfidToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::AccountToSfid` (r:1 w:1)
	/// Proof: `SfidSystem::AccountToSfid` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::BoundCount` (r:1 w:1)
	/// Proof: `SfidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::CredentialNoncesByExpiry` (r:1 w:1)
	/// Proof: `SfidSystem::CredentialNoncesByExpiry` (`max_values`: None, `max_size`: Some(6400024), added: 6402499, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardClaimed` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bind_sfid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `237`
		//  Estimated: `6403489`
		// Minimum execution time: 148_507_000 picoseconds.
		Weight::from_parts(151_332_000, 0)
			.saturating_add(Weight::from_parts(0, 6403489))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `SfidSystem::SfidMainAccount` (r:1 w:0)
	/// Proof: `SfidSystem::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::ProvinceBySigningPubkey` (r:1 w:0)
	/// Proof: `SfidSystem::ProvinceBySigningPubkey` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::AccountToBindingId` (r:1 w:1)
	/// Proof: `SfidSystem::AccountToBindingId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::BoundCount` (r:1 w:1)
	/// Proof: `SfidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::BindingIdToAccount` (r:0 w:1)
	/// Proof: `SfidSystem::BindingIdToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn unbind_sfid() -> Weight {
		// 管理员代为解绑：4 reads（主账户 + 省级公钥 + 账户映射 + 计数）+ 3 writes
		Weight::from_parts(28_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3562))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SfidSystem::SfidMainAccount` (r:1 w:1)
	/// Proof: `SfidSystem::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::SfidBackupAccount1` (r:1 w:1)
	/// Proof: `SfidSystem::SfidBackupAccount1` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::SfidBackupAccount2` (r:1 w:1)
	/// Proof: `SfidSystem::SfidBackupAccount2` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn rotate_sfid_keys() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `202`
		//  Estimated: `1517`
		// Minimum execution time: 20_217_000 picoseconds.
		Weight::from_parts(20_839_000, 0)
			.saturating_add(Weight::from_parts(0, 1517))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

impl WeightInfo for () {
	/// Storage: `SfidSystem::UsedCredentialNonce` (r:1 w:1)
	/// Proof: `SfidSystem::UsedCredentialNonce` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::SfidMainAccount` (r:1 w:0)
	/// Proof: `SfidSystem::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::SfidToAccount` (r:1 w:1)
	/// Proof: `SfidSystem::SfidToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::AccountToSfid` (r:1 w:1)
	/// Proof: `SfidSystem::AccountToSfid` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::BoundCount` (r:1 w:1)
	/// Proof: `SfidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::CredentialNoncesByExpiry` (r:1 w:1)
	/// Proof: `SfidSystem::CredentialNoncesByExpiry` (`max_values`: None, `max_size`: Some(6400024), added: 6402499, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardClaimed` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bind_sfid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `237`
		//  Estimated: `6403489`
		// Minimum execution time: 148_507_000 picoseconds.
		Weight::from_parts(151_332_000, 0)
			.saturating_add(Weight::from_parts(0, 6403489))
			.saturating_add(RocksDbWeight::get().reads(11))
			.saturating_add(RocksDbWeight::get().writes(9))
	}
	/// Storage: `SfidSystem::SfidMainAccount` (r:1 w:0)
	/// Proof: `SfidSystem::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::ProvinceBySigningPubkey` (r:1 w:0)
	/// Proof: `SfidSystem::ProvinceBySigningPubkey` (`max_values`: None, `max_size`: Some(97), added: 2572, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::AccountToBindingId` (r:1 w:1)
	/// Proof: `SfidSystem::AccountToBindingId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::BoundCount` (r:1 w:1)
	/// Proof: `SfidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::BindingIdToAccount` (r:0 w:1)
	/// Proof: `SfidSystem::BindingIdToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn unbind_sfid() -> Weight {
		// 管理员代为解绑：4 reads（主账户 + 省级公钥 + 账户映射 + 计数）+ 3 writes
		Weight::from_parts(28_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3562))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: `SfidSystem::SfidMainAccount` (r:1 w:1)
	/// Proof: `SfidSystem::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::SfidBackupAccount1` (r:1 w:1)
	/// Proof: `SfidSystem::SfidBackupAccount1` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidSystem::SfidBackupAccount2` (r:1 w:1)
	/// Proof: `SfidSystem::SfidBackupAccount2` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn rotate_sfid_keys() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `202`
		//  Estimated: `1517`
		// Minimum execution time: 20_217_000 picoseconds.
		Weight::from_parts(20_839_000, 0)
			.saturating_add(Weight::from_parts(0, 1517))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
