
//! Autogenerated weights for `resolution_destro_gov`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm0kj6c`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /home/runner/work/GMB/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// resolution_destro_gov
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /home/runner/work/GMB/GMB/citizenchain/governance/resolution-destro-gov/src/weights.rs
// --template
// /home/runner/work/GMB/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `resolution_destro_gov`.
pub trait WeightInfo {
	fn propose_destroy() -> Weight;
	fn vote_destroy() -> Weight;
	fn execute_destroy() -> Weight;
	fn cancel_stale_destroy() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngineSystem::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngineSystem::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn propose_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1176`
		//  Estimated: `19871`
		// Minimum execution time: 51_215_000 picoseconds.
		Weight::from_parts(52_228_000, 0)
			.saturating_add(Weight::from_parts(0, 19871))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:1 w:1)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngineSystem::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn vote_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2033`
		//  Estimated: `4554`
		// Minimum execution time: 129_240_000 picoseconds.
		Weight::from_parts(131_174_000, 0)
			.saturating_add(Weight::from_parts(0, 4554))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngineSystem::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn execute_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `751`
		//  Estimated: `3593`
		// Minimum execution time: 73_145_000 picoseconds.
		Weight::from_parts(74_859_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngineSystem::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn cancel_stale_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `593`
		//  Estimated: `3559`
		// Minimum execution time: 47_609_000 picoseconds.
		Weight::from_parts(48_470_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(7))
	}
}

impl WeightInfo for () {
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngineSystem::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngineSystem::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn propose_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1176`
		//  Estimated: `19871`
		// Minimum execution time: 51_215_000 picoseconds.
		Weight::from_parts(52_228_000, 0)
			.saturating_add(Weight::from_parts(0, 19871))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:1 w:1)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngineSystem::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn vote_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2033`
		//  Estimated: `4554`
		// Minimum execution time: 129_240_000 picoseconds.
		Weight::from_parts(131_174_000, 0)
			.saturating_add(Weight::from_parts(0, 4554))
			.saturating_add(RocksDbWeight::get().reads(8))
			.saturating_add(RocksDbWeight::get().writes(9))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngineSystem::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn execute_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `751`
		//  Estimated: `3593`
		// Minimum execution time: 73_145_000 picoseconds.
		Weight::from_parts(74_859_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::PendingProposalCleanups` (r:0 w:1)
	/// Proof: `VotingEngineSystem::PendingProposalCleanups` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn cancel_stale_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `593`
		//  Estimated: `3559`
		// Minimum execution time: 47_609_000 picoseconds.
		Weight::from_parts(48_470_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(7))
	}
}
