
//! Autogenerated weights for `resolution_destro_gov`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-12, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /Users/rhett/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// resolution_destro_gov
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /Users/rhett/GMB/citizenchain/governance/resolution-destro-gov/src/weights.rs
// --template
// /Users/rhett/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `resolution_destro_gov`.
pub trait WeightInfo {
	fn propose_destroy() -> Weight;
	fn vote_destroy() -> Weight;
	fn execute_destroy() -> Weight;
	fn cancel_stale_destroy() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngineSystem::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngineSystem::ProposalsByExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn propose_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1176`
		//  Estimated: `4641`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4641))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(6))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:6 w:6)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn vote_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2116`
		//  Estimated: `16278`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(61_000_000, 0)
			.saturating_add(Weight::from_parts(0, 16278))
			.saturating_add(T::DbWeight::get().reads(13))
			.saturating_add(T::DbWeight::get().writes(13))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:6 w:6)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn execute_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1091`
		//  Estimated: `16278`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(35_000_000, 0)
			.saturating_add(Weight::from_parts(0, 16278))
			.saturating_add(T::DbWeight::get().reads(10))
			.saturating_add(T::DbWeight::get().writes(13))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn cancel_stale_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `593`
		//  Estimated: `3559`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(T::DbWeight::get().reads(4))
			.saturating_add(T::DbWeight::get().writes(6))
	}
}

impl WeightInfo for () {
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngineSystem::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngineSystem::ProposalsByExpiry` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `VotingEngineSystem::Proposals` (r:0 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn propose_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1176`
		//  Estimated: `4641`
		// Minimum execution time: 19_000_000 picoseconds.
		Weight::from_parts(20_000_000, 0)
			.saturating_add(Weight::from_parts(0, 4641))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `AdminsOriginGov::CurrentAdmins` (r:1 w:0)
	/// Proof: `AdminsOriginGov::CurrentAdmins` (`max_values`: None, `max_size`: Some(1089), added: 3564, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:6 w:6)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:1 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn vote_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `2116`
		//  Estimated: `16278`
		// Minimum execution time: 57_000_000 picoseconds.
		Weight::from_parts(61_000_000, 0)
			.saturating_add(Weight::from_parts(0, 16278))
			.saturating_add(RocksDbWeight::get().reads(13))
			.saturating_add(RocksDbWeight::get().writes(13))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalVotesByAccount` (r:6 w:6)
	/// Proof: `VotingEngineSystem::InternalVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn execute_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1091`
		//  Estimated: `16278`
		// Minimum execution time: 34_000_000 picoseconds.
		Weight::from_parts(35_000_000, 0)
			.saturating_add(Weight::from_parts(0, 16278))
			.saturating_add(RocksDbWeight::get().reads(10))
			.saturating_add(RocksDbWeight::get().writes(13))
	}
	/// Storage: `ResolutionDestroGov::ProposalActions` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalActions` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalCreatedAt` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ProposalCreatedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::Proposals` (r:1 w:1)
	/// Proof: `VotingEngineSystem::Proposals` (`max_values`: None, `max_size`: Some(94), added: 2569, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ActiveProposalByInstitution` (r:1 w:1)
	/// Proof: `ResolutionDestroGov::ActiveProposalByInstitution` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngineSystem::InternalTallies` (r:0 w:1)
	/// Proof: `VotingEngineSystem::InternalTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `ResolutionDestroGov::ProposalPassedAt` (r:0 w:1)
	/// Proof: `ResolutionDestroGov::ProposalPassedAt` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	fn cancel_stale_destroy() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `593`
		//  Estimated: `3559`
		// Minimum execution time: 20_000_000 picoseconds.
		Weight::from_parts(21_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3559))
			.saturating_add(RocksDbWeight::get().reads(4))
			.saturating_add(RocksDbWeight::get().writes(6))
	}
}
