
//! Autogenerated weights for `runtime_upgrade`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-15, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --runtime=target/release/wbuild/citizenchain/citizenchain.compact.compressed.wasm
// --genesis-builder=spec-genesis
// --pallet=runtime_upgrade
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=scripts/benchmark-weight-template.hbs
// --output=runtime/governance/runtime-upgrade/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `runtime_upgrade`.
pub trait WeightInfo {
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PublicAdmins::AdminAccounts` (r:87 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(63736), added: 66211, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::PendingPopulationSnapshots` (r:1 w:1)
	/// Proof: `JointVote::PendingPopulationSnapshots` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:87 w:87)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:87 w:87)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshotIds` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalPopulationSnapshotIds` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalObjectMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalObjectMeta` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCid` (r:0 w:87)
	/// Proof: `VotingEngine::ProposalsByCid` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AdminSnapshot` (r:0 w:87)
	/// Proof: `VotingEngine::AdminSnapshot` (`max_values`: None, `max_size`: Some(63722), added: 66197, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalObject` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalObject` (`max_values`: None, `max_size`: Some(10485788), added: 10488263, mode: `MaxEncodedLen`)
	fn propose_runtime_upgrade() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PublicAdmins::AdminAccounts` (r:87 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(63736), added: 66211, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::PendingPopulationSnapshots` (r:1 w:1)
	/// Proof: `JointVote::PendingPopulationSnapshots` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:87 w:87)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:87 w:87)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshotIds` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalPopulationSnapshotIds` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalObjectMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalObjectMeta` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCid` (r:0 w:87)
	/// Proof: `VotingEngine::ProposalsByCid` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AdminSnapshot` (r:0 w:87)
	/// Proof: `VotingEngine::AdminSnapshot` (`max_values`: None, `max_size`: Some(63722), added: 66197, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalObject` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalObject` (`max_values`: None, `max_size`: Some(10485788), added: 10488263, mode: `MaxEncodedLen`)
	fn propose_runtime_upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `31323`
		//  Estimated: `5761347`
		// Minimum execution time: 8_662_000_000 picoseconds.
		Weight::from_parts(8_714_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5761347))
			.saturating_add(T::DbWeight::get().reads(271))
			.saturating_add(T::DbWeight::get().writes(364))
	}
}

impl WeightInfo for () {
	/// Storage: `PowDifficulty::ActiveParams` (r:1 w:0)
	/// Proof: `PowDifficulty::ActiveParams` (`max_values`: Some(1), `max_size`: Some(34), added: 529, mode: `MaxEncodedLen`)
	/// Storage: `PublicAdmins::AdminAccounts` (r:87 w:0)
	/// Proof: `PublicAdmins::AdminAccounts` (`max_values`: None, `max_size`: Some(63736), added: 66211, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::PendingPopulationSnapshots` (r:1 w:1)
	/// Proof: `JointVote::PendingPopulationSnapshots` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `Timestamp::Now` (r:1 w:0)
	/// Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::NextProposalId` (r:1 w:1)
	/// Proof: `VotingEngine::NextProposalId` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CurrentProposalYear` (r:1 w:1)
	/// Proof: `VotingEngine::CurrentProposalYear` (`max_values`: Some(1), `max_size`: Some(2), added: 497, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:87 w:87)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::InternalProposalMutexes` (r:87 w:87)
	/// Proof: `VotingEngine::InternalProposalMutexes` (`max_values`: None, `max_size`: Some(63), added: 2538, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshotIds` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalPopulationSnapshotIds` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalOwner` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalData` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalData` (`max_values`: None, `max_size`: Some(102428), added: 104903, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalObjectMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalObjectMeta` (`max_values`: None, `max_size`: Some(61), added: 2536, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByOwner` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByOwner` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByYear` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalsByYear` (`max_values`: None, `max_size`: Some(26), added: 2501, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:0 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8531), added: 11006, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByCid` (r:0 w:87)
	/// Proof: `VotingEngine::ProposalsByCid` (`max_values`: None, `max_size`: Some(57), added: 2532, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalDisplayId` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalDisplayId` (`max_values`: None, `max_size`: Some(30), added: 2505, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AdminSnapshot` (r:0 w:87)
	/// Proof: `VotingEngine::AdminSnapshot` (`max_values`: None, `max_size`: Some(63722), added: 66197, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::YearProposalCounter` (r:0 w:1)
	/// Proof: `VotingEngine::YearProposalCounter` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalObject` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalObject` (`max_values`: None, `max_size`: Some(10485788), added: 10488263, mode: `MaxEncodedLen`)
	fn propose_runtime_upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `31323`
		//  Estimated: `5761347`
		// Minimum execution time: 8_662_000_000 picoseconds.
		Weight::from_parts(8_714_000_000, 0)
			.saturating_add(Weight::from_parts(0, 5761347))
			.saturating_add(RocksDbWeight::get().reads(271))
			.saturating_add(RocksDbWeight::get().writes(364))
	}
}
