
//! Autogenerated weights for `runtime_upgrade`
//!
//! 注意：当前权重数值仍为保守 fallback，正式数值由 CI benchmark 流程更新。
//! 本文件不再保留旧 runtime-upgrade 本地提案存储的 proof 注释。
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm46oaq`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("citizenchain")`, DB CACHE: 1024

// Executed Command:
// /home/runner/work/GMB/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// citizenchain
// --pallet
// runtime_upgrade
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /home/runner/work/GMB/GMB/citizenchain/runtime/governance/runtime-upgrade/src/weights.rs
// --template
// /home/runner/work/GMB/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `runtime_upgrade`.
pub trait WeightInfo {
	fn propose_runtime_upgrade() -> Weight;
}

	pub struct SubstrateWeight<T>(PhantomData<T>);
	impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
		fn propose_runtime_upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1562`
		//  Estimated: `19871`
		// Minimum execution time: 12_110_923_000 picoseconds.
		Weight::from_parts(12_244_812_000, 0)
			.saturating_add(Weight::from_parts(0, 19871))
			.saturating_add(T::DbWeight::get().reads(5))
			.saturating_add(T::DbWeight::get().writes(8))
	}
}

	impl WeightInfo for () {
		fn propose_runtime_upgrade() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1562`
		//  Estimated: `19871`
		// Minimum execution time: 12_110_923_000 picoseconds.
		Weight::from_parts(12_244_812_000, 0)
			.saturating_add(Weight::from_parts(0, 19871))
			.saturating_add(RocksDbWeight::get().reads(5))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
}
