use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::PathBuf,
};

#[derive(Debug)]
struct Province {
    name: String,
    code: String,
}

fn main() {
    // 省市代码在编译期固化进二进制，避免运行时依赖外部文件。
    println!("cargo:rerun-if-env-changed=CPMS_SFID_DIR");
    println!("cargo:rerun-if-env-changed=CPMS_SFID_TOOL_DIR");

    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR missing"));
    let sfid_dir = env::var("CPMS_SFID_DIR")
        .or_else(|_| env::var("CPMS_SFID_TOOL_DIR"))
        .map(PathBuf::from)
        .unwrap_or_else(|_| manifest_dir.join("../../sfid/backend/src/sfid"));

    let province_file = sfid_dir.join("province.rs");
    let city_dir = sfid_dir.join("city_codes");

    if !province_file.is_file() || !city_dir.is_dir() {
        panic!(
            "sfid source not found. expected province file at '{}' and city dir at '{}'. \
set CPMS_SFID_DIR to '/path/to/sfid/backend/src/sfid'",
            province_file.display(),
            city_dir.display()
        );
    }

    println!("cargo:rerun-if-changed={}", province_file.display());
    let provinces_src = fs::read_to_string(&province_file)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", province_file.display()));
    let provinces = parse_provinces(&provinces_src);
    if provinces.is_empty() {
        panic!("no provinces parsed from {}", province_file.display());
    }

    let mut city_map: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for entry in fs::read_dir(&city_dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", city_dir.display()))
    {
        let entry = entry.unwrap_or_else(|e| panic!("read_dir entry error: {e}"));
        let path = entry.path();
        if path.extension().and_then(|s| s.to_str()) != Some("rs") {
            continue;
        }
        println!("cargo:rerun-if-changed={}", path.display());

        let filename = path.file_name().and_then(|s| s.to_str()).unwrap_or("");
        let province_code = parse_city_file_province_code(filename)
            .unwrap_or_else(|| panic!("invalid city file name: {}", path.display()));
        let src = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        // 以“市代码”为唯一键去重，避免上游重复定义导致生成代码冲突。
        let cities = parse_cities(&src);
        city_map.insert(province_code.to_string(), dedup_cities(cities));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR missing"));
    let out_file = out_dir.join("sfid_province_city.rs");
    let generated = generate_module(&provinces, &city_map);
    fs::write(&out_file, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_file.display()));
}

fn parse_provinces(src: &str) -> Vec<Province> {
    let mut out = Vec::new();
    for line in src.lines() {
        if !line.contains("ProvinceCode {") {
            continue;
        }
        let name = extract_field(line, "name: \"");
        let code = extract_field(line, "code: \"");
        if let (Some(name), Some(code)) = (name, code) {
            out.push(Province { name, code });
        }
    }
    out
}

fn parse_cities(src: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for line in src.lines() {
        if !line.contains("CityCode {") {
            continue;
        }
        let name = extract_field(line, "name: \"");
        let code = extract_field(line, "code: \"");
        if let (Some(name), Some(code)) = (name, code) {
            out.push((name, code));
        }
    }
    out
}

fn dedup_cities(cities: Vec<(String, String)>) -> Vec<(String, String)> {
    let mut seen = BTreeSet::new();
    let mut out = Vec::new();
    for (name, code) in cities {
        if seen.insert(code.clone()) {
            out.push((name, code));
        }
    }
    out
}

fn parse_city_file_province_code(filename: &str) -> Option<&str> {
    let mut parts = filename.split('_');
    let _index = parts.next()?;
    let code_with_ext = parts.next()?;
    code_with_ext.strip_suffix(".rs")
}

fn extract_field(line: &str, marker: &str) -> Option<String> {
    let start = line.find(marker)? + marker.len();
    let rest = &line[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

fn generate_module(
    provinces: &[Province],
    city_map: &BTreeMap<String, Vec<(String, String)>>,
) -> String {
    // 直接生成 Rust 常量与校验函数，后端仅调用，不再维护本地省市码表。
    let mut out = String::new();
    out.push_str("// @generated by build.rs from SFID sfid\n\n");

    out.push_str(&format!(
        "pub const PROVINCES: [(&str, &str); {}] = [\n",
        provinces.len()
    ));
    for p in provinces {
        out.push_str(&format!(
            "    (\"{}\", \"{}\"),\n",
            escape_rust_str(&p.name),
            escape_rust_str(&p.code)
        ));
    }
    out.push_str("];\n\n");

    for p in provinces {
        let cities = city_map.get(&p.code).unwrap_or_else(|| {
            panic!(
                "missing city code file for province {} ({})",
                p.name, p.code
            )
        });
        out.push_str(&format!(
            "const CITIES_{}: [(&str, &str); {}] = [\n",
            p.code,
            cities.len()
        ));
        for (city_name, city_code) in cities {
            out.push_str(&format!(
                "    (\"{}\", \"{}\"),\n",
                escape_rust_str(city_name),
                escape_rust_str(city_code)
            ));
        }
        out.push_str("];\n\n");
    }

    out.push_str("pub fn is_valid_province_code(code: &str) -> bool {\n");
    out.push_str("    PROVINCES.iter().any(|(_, province_code)| *province_code == code)\n");
    out.push_str("}\n\n");

    out.push_str(
        "pub fn is_valid_city_code_for_province(province_code: &str, city_code: &str) -> bool {\n",
    );
    out.push_str("    match province_code {\n");
    for p in provinces {
        out.push_str(&format!(
            "        \"{}\" => CITIES_{}.iter().any(|(_, code)| *code == city_code),\n",
            escape_rust_str(&p.code),
            p.code
        ));
    }
    out.push_str("        _ => false,\n");
    out.push_str("    }\n");
    out.push_str("}\n");

    out
}

fn escape_rust_str(v: &str) -> String {
    let mut out = String::with_capacity(v.len());
    for ch in v.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            _ => out.push(ch),
        }
    }
    out
}
