
//! Autogenerated weights for `shengbank_stake_interest`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm46oaq`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /home/runner/work/GMB/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// shengbank_stake_interest
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /home/runner/work/GMB/GMB/citizenchain/issuance/shengbank-stake-interest/src/weights.rs
// --template
// /home/runner/work/GMB/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `shengbank_stake_interest`.
pub trait WeightInfo {
	fn force_settle_years(y: u32, ) -> Weight;
	fn force_advance_year() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ShengBankStakeInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankStakeInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `y` is `[1, 100]`.
	fn force_settle_years(y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1189`
		//  Estimated: `112919`
		// Minimum execution time: 1_150_023_000 picoseconds.
		Weight::from_parts(580_787_056, 0)
			.saturating_add(Weight::from_parts(0, 112919))
			// Standard Error: 561_139
			.saturating_add(Weight::from_parts(698_038_295, 0).saturating_mul(y.into()))
			.saturating_add(T::DbWeight::get().reads(44))
			.saturating_add(T::DbWeight::get().writes(44))
	}
	/// Storage: `ShengBankStakeInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankStakeInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn force_advance_year() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `1489`
		// Minimum execution time: 13_315_000 picoseconds.
		Weight::from_parts(14_107_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	/// Storage: `ShengBankStakeInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankStakeInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:43 w:43)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// The range of component `y` is `[1, 100]`.
	fn force_settle_years(y: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1189`
		//  Estimated: `112919`
		// Minimum execution time: 1_150_023_000 picoseconds.
		Weight::from_parts(580_787_056, 0)
			.saturating_add(Weight::from_parts(0, 112919))
			// Standard Error: 561_139
			.saturating_add(Weight::from_parts(698_038_295, 0).saturating_mul(y.into()))
			.saturating_add(RocksDbWeight::get().reads(44))
			.saturating_add(RocksDbWeight::get().writes(44))
	}
	/// Storage: `ShengBankStakeInterest::LastSettledYear` (r:1 w:1)
	/// Proof: `ShengBankStakeInterest::LastSettledYear` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn force_advance_year() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `69`
		//  Estimated: `1489`
		// Minimum execution time: 13_315_000 picoseconds.
		Weight::from_parts(14_107_000, 0)
			.saturating_add(Weight::from_parts(0, 1489))
			.saturating_add(RocksDbWeight::get().reads(1))
			.saturating_add(RocksDbWeight::get().writes(1))
	}
}
