
//! Autogenerated weights for `cid_system`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-06-22, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --runtime=/Users/rhett/GMB/citizenchain/target/release/wbuild/citizenchain/citizenchain.compact.compressed.wasm
// --genesis-builder=spec-genesis
// --pallet=cid_system
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=/Users/rhett/GMB/citizenchain/scripts/benchmark-weight-template.hbs
// --output=runtime/otherpallet/cid-system/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `cid_system`.
pub trait WeightInfo {
	/// Storage: `CidSystem::UsedBindNonce` (r:1 w:1)
	/// Proof: `CidSystem::UsedBindNonce` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BindingIdToAccount` (r:1 w:1)
	/// Proof: `CidSystem::BindingIdToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::AccountToBindingId` (r:1 w:1)
	/// Proof: `CidSystem::AccountToBindingId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BoundCount` (r:1 w:1)
	/// Proof: `CidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardClaimed` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bind_cid() -> Weight;
	/// Storage: `CidSystem::AccountToBindingId` (r:1 w:1)
	/// Proof: `CidSystem::AccountToBindingId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BoundCount` (r:1 w:1)
	/// Proof: `CidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BindingIdToAccount` (r:0 w:1)
	/// Proof: `CidSystem::BindingIdToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn unbind_cid() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `CidSystem::UsedBindNonce` (r:1 w:1)
	/// Proof: `CidSystem::UsedBindNonce` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BindingIdToAccount` (r:1 w:1)
	/// Proof: `CidSystem::BindingIdToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::AccountToBindingId` (r:1 w:1)
	/// Proof: `CidSystem::AccountToBindingId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BoundCount` (r:1 w:1)
	/// Proof: `CidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardClaimed` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bind_cid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3593`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(32_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `CidSystem::AccountToBindingId` (r:1 w:1)
	/// Proof: `CidSystem::AccountToBindingId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BoundCount` (r:1 w:1)
	/// Proof: `CidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BindingIdToAccount` (r:0 w:1)
	/// Proof: `CidSystem::BindingIdToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn unbind_cid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `154`
		//  Estimated: `3545`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

impl WeightInfo for () {
	/// Storage: `CidSystem::UsedBindNonce` (r:1 w:1)
	/// Proof: `CidSystem::UsedBindNonce` (`max_values`: None, `max_size`: Some(49), added: 2524, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BindingIdToAccount` (r:1 w:1)
	/// Proof: `CidSystem::BindingIdToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::AccountToBindingId` (r:1 w:1)
	/// Proof: `CidSystem::AccountToBindingId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BoundCount` (r:1 w:1)
	/// Proof: `CidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardClaimed` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardClaimed` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bind_cid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `42`
		//  Estimated: `3593`
		// Minimum execution time: 31_000_000 picoseconds.
		Weight::from_parts(32_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3593))
			.saturating_add(RocksDbWeight::get().reads(8))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
	/// Storage: `CidSystem::AccountToBindingId` (r:1 w:1)
	/// Proof: `CidSystem::AccountToBindingId` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BoundCount` (r:1 w:1)
	/// Proof: `CidSystem::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `CidSystem::BindingIdToAccount` (r:0 w:1)
	/// Proof: `CidSystem::BindingIdToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn unbind_cid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `154`
		//  Estimated: `3545`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
