
//! Autogenerated weights for `joint_vote`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-07-20, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `rhettdeMacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.lPhB6Q0oPM")`, DB CACHE: 1024

// Executed Command:
// ./target/release/citizenchain
// benchmark
// pallet
// --chain=/var/folders/z1/h1pvtv0x76xg5h60y_2npmbc0000gn/T/citizenchain-benchmark-spec.lPhB6Q0oPM
// --genesis-builder=spec-genesis
// --pallet=joint_vote
// --extrinsic=*
// --steps=50
// --repeat=20
// --template=scripts/benchmark-weight-template.hbs
// --output=runtime/votingengine/joint-vote/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
	traits::Get,
	weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `joint_vote`.
pub trait WeightInfo {
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointVotesByInstitution` (r:1 w:1)
	/// Proof: `JointVote::JointVotesByInstitution` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::EffectiveVoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::EffectiveVoterSnapshot` (`max_values`: None, `max_size`: Some(63724), added: 66199, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointVotesByAdmin` (r:1 w:1)
	/// Proof: `JointVote::JointVotesByAdmin` (`max_values`: None, `max_size`: Some(106), added: 2581, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointInstitutionTallies` (r:1 w:1)
	/// Proof: `JointVote::JointInstitutionTallies` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointTallies` (r:1 w:1)
	/// Proof: `JointVote::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn cast_admin() -> Weight;
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::ReferendumVotesByAccount` (r:1 w:1)
	/// Proof: `JointVote::ReferendumVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::ReferendumTallies` (r:1 w:1)
	/// Proof: `JointVote::ReferendumTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn cast_referendum() -> Weight;
	/// Storage: `JointVote::JointTallies` (r:1 w:0)
	/// Proof: `JointVote::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:2 w:2)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	fn finalize_joint_timeout() -> Weight;
	/// Storage: `JointVote::ReferendumTallies` (r:1 w:0)
	/// Proof: `JointVote::ReferendumTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanupTail` (r:1 w:1)
	/// Proof: `VotingEngine::ScheduledCleanupTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::ScheduledCleanups` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CallbackExecutionScopes` (r:0 w:1)
	/// Proof: `VotingEngine::CallbackExecutionScopes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingExecutionRetryExpirations` (r:0 w:1)
	/// Proof: `VotingEngine::PendingExecutionRetryExpirations` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingTerminalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingTerminalCleanups` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_jointreferendum_timeout() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointVotesByInstitution` (r:1 w:1)
	/// Proof: `JointVote::JointVotesByInstitution` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::EffectiveVoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::EffectiveVoterSnapshot` (`max_values`: None, `max_size`: Some(63724), added: 66199, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointVotesByAdmin` (r:1 w:1)
	/// Proof: `JointVote::JointVotesByAdmin` (`max_values`: None, `max_size`: Some(106), added: 2581, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointInstitutionTallies` (r:1 w:1)
	/// Proof: `JointVote::JointInstitutionTallies` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointTallies` (r:1 w:1)
	/// Proof: `JointVote::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn cast_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1014`
		//  Estimated: `67189`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(26_000_000, 0)
			.saturating_add(Weight::from_parts(0, 67189))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::ReferendumVotesByAccount` (r:1 w:1)
	/// Proof: `JointVote::ReferendumVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::ReferendumTallies` (r:1 w:1)
	/// Proof: `JointVote::ReferendumTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn cast_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `573`
		//  Estimated: `12022`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(39_000_000, 0)
			.saturating_add(Weight::from_parts(0, 12022))
			.saturating_add(T::DbWeight::get().reads(8))
			.saturating_add(T::DbWeight::get().writes(8))
	}
	/// Storage: `JointVote::JointTallies` (r:1 w:0)
	/// Proof: `JointVote::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:2 w:2)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	fn finalize_joint_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `282`
		//  Estimated: `38752`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(Weight::from_parts(0, 38752))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `JointVote::ReferendumTallies` (r:1 w:0)
	/// Proof: `JointVote::ReferendumTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanupTail` (r:1 w:1)
	/// Proof: `VotingEngine::ScheduledCleanupTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::ScheduledCleanups` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CallbackExecutionScopes` (r:0 w:1)
	/// Proof: `VotingEngine::CallbackExecutionScopes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingExecutionRetryExpirations` (r:0 w:1)
	/// Proof: `VotingEngine::PendingExecutionRetryExpirations` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingTerminalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingTerminalCleanups` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_jointreferendum_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `282`
		//  Estimated: `12451`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(25_000_000, 0)
			.saturating_add(Weight::from_parts(0, 12451))
			.saturating_add(T::DbWeight::get().reads(6))
			.saturating_add(T::DbWeight::get().writes(10))
	}
}

impl WeightInfo for () {
	/// Storage: `VotingEngine::Proposals` (r:1 w:0)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointVotesByInstitution` (r:1 w:1)
	/// Proof: `JointVote::JointVotesByInstitution` (`max_values`: None, `max_size`: Some(74), added: 2549, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::EffectiveVoterSnapshot` (r:1 w:0)
	/// Proof: `VotingEngine::EffectiveVoterSnapshot` (`max_values`: None, `max_size`: Some(63724), added: 66199, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointVotesByAdmin` (r:1 w:1)
	/// Proof: `JointVote::JointVotesByAdmin` (`max_values`: None, `max_size`: Some(106), added: 2581, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointInstitutionTallies` (r:1 w:1)
	/// Proof: `JointVote::JointInstitutionTallies` (`max_values`: None, `max_size`: Some(81), added: 2556, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::JointTallies` (r:1 w:1)
	/// Proof: `JointVote::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	fn cast_admin() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1014`
		//  Estimated: `67189`
		// Minimum execution time: 26_000_000 picoseconds.
		Weight::from_parts(26_000_000, 0)
			.saturating_add(Weight::from_parts(0, 67189))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(4))
	}
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersionCount` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersionCount` (`max_values`: None, `max_size`: Some(56), added: 2531, mode: `MaxEncodedLen`)
	/// Storage: `CitizenIdentity::VotingEligibilityVersions` (r:1 w:0)
	/// Proof: `CitizenIdentity::VotingEligibilityVersions` (`max_values`: None, `max_size`: Some(186), added: 2661, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::ReferendumVotesByAccount` (r:1 w:1)
	/// Proof: `JointVote::ReferendumVotesByAccount` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `JointVote::ReferendumTallies` (r:1 w:1)
	/// Proof: `JointVote::ReferendumTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMeta` (r:1 w:1)
	/// Proof: `VotingEngine::ProposalMeta` (`max_values`: None, `max_size`: Some(33), added: 2508, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingProposalExecutions` (r:0 w:1)
	/// Proof: `VotingEngine::PendingProposalExecutions` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	fn cast_referendum() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `573`
		//  Estimated: `12022`
		// Minimum execution time: 37_000_000 picoseconds.
		Weight::from_parts(39_000_000, 0)
			.saturating_add(Weight::from_parts(0, 12022))
			.saturating_add(RocksDbWeight::get().reads(8))
			.saturating_add(RocksDbWeight::get().writes(8))
	}
	/// Storage: `JointVote::JointTallies` (r:1 w:0)
	/// Proof: `JointVote::JointTallies` (`max_values`: None, `max_size`: Some(32), added: 2507, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalsByExpiry` (r:2 w:2)
	/// Proof: `VotingEngine::ProposalsByExpiry` (`max_values`: None, `max_size`: Some(16406), added: 18881, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	fn finalize_joint_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `282`
		//  Estimated: `38752`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(Weight::from_parts(0, 38752))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: `JointVote::ReferendumTallies` (r:1 w:0)
	/// Proof: `JointVote::ReferendumTallies` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalPopulationSnapshots` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalPopulationSnapshots` (`max_values`: None, `max_size`: Some(100), added: 2575, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::Proposals` (r:1 w:1)
	/// Proof: `VotingEngine::Proposals` (`max_values`: None, `max_size`: Some(8557), added: 11032, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ActiveProposalsBySubject` (r:1 w:1)
	/// Proof: `VotingEngine::ActiveProposalsBySubject` (`max_values`: None, `max_size`: Some(131), added: 2606, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanupTail` (r:1 w:1)
	/// Proof: `VotingEngine::ScheduledCleanupTail` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalMutexBindings` (r:1 w:0)
	/// Proof: `VotingEngine::ProposalMutexBindings` (`max_values`: None, `max_size`: Some(8986), added: 11461, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ScheduledCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::ScheduledCleanups` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeRetryStates` (`max_values`: None, `max_size`: Some(29), added: 2504, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::AutoFinalizeDeadLetters` (r:0 w:1)
	/// Proof: `VotingEngine::AutoFinalizeDeadLetters` (`max_values`: None, `max_size`: Some(25), added: 2500, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::CallbackExecutionScopes` (r:0 w:1)
	/// Proof: `VotingEngine::CallbackExecutionScopes` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingExecutionRetryExpirations` (r:0 w:1)
	/// Proof: `VotingEngine::PendingExecutionRetryExpirations` (`max_values`: None, `max_size`: Some(28), added: 2503, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::ProposalExecutionRetryStates` (r:0 w:1)
	/// Proof: `VotingEngine::ProposalExecutionRetryStates` (`max_values`: None, `max_size`: Some(38), added: 2513, mode: `MaxEncodedLen`)
	/// Storage: `VotingEngine::PendingTerminalCleanups` (r:0 w:1)
	/// Proof: `VotingEngine::PendingTerminalCleanups` (`max_values`: None, `max_size`: Some(24), added: 2499, mode: `MaxEncodedLen`)
	fn finalize_jointreferendum_timeout() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `282`
		//  Estimated: `12451`
		// Minimum execution time: 24_000_000 picoseconds.
		Weight::from_parts(25_000_000, 0)
			.saturating_add(Weight::from_parts(0, 12451))
			.saturating_add(RocksDbWeight::get().reads(6))
			.saturating_add(RocksDbWeight::get().writes(10))
	}
}
