name: wuminapp_mobile
description: WuminApp light-node mobile client built with Flutter.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  polkadart: ^0.7.0
  polkadart_keyring: ^0.7.0
  bip39: ^1.0.6
  mobile_scanner: ^7.1.4
  qr_flutter: ^4.1.0
  flutter_svg: ^2.0.10+1
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2
  crypto: ^3.0.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/scan-line.svg
    - assets/icons/wallet.svg
    - assets/icons/copy.svg
    - assets/icons/arrow-right-left.svg
    - assets/icons/file-user.svg
    - assets/icons/message-square-text.svg
    - assets/icons/scale.svg
    - assets/icons/contact-round.svg
