
//! Autogenerated weights for `sfid_code_auth`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 53.0.0
//! DATE: 2026-03-14, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runnervm46oaq`, CPU: `AMD EPYC 7763 64-Core Processor`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("mainnet")`, DB CACHE: 1024

// Executed Command:
// /home/runner/work/GMB/GMB/citizenchain/target/release/node
// benchmark
// pallet
// --chain
// mainnet
// --pallet
// sfid_code_auth
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --wasm-execution
// compiled
// --heap-pages
// 4096
// --output
// /home/runner/work/GMB/GMB/citizenchain/otherpallet/sfid-code-auth/src/weights.rs
// --template
// /home/runner/work/GMB/GMB/citizenchain/scripts/benchmark-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use core::marker::PhantomData;
use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};

/// Weight functions for `sfid_code_auth`.
pub trait WeightInfo {
	fn bind_sfid() -> Weight;
	fn unbind_sfid() -> Weight;
	fn rotate_sfid_keys() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `SfidCodeAuth::UsedCredentialNonce` (r:1 w:1)
	/// Proof: `SfidCodeAuth::UsedCredentialNonce` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidMainAccount` (r:1 w:0)
	/// Proof: `SfidCodeAuth::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidToAccount` (r:1 w:1)
	/// Proof: `SfidCodeAuth::SfidToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::AccountToSfid` (r:1 w:1)
	/// Proof: `SfidCodeAuth::AccountToSfid` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::BoundCount` (r:1 w:1)
	/// Proof: `SfidCodeAuth::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::CredentialNoncesByExpiry` (r:1 w:1)
	/// Proof: `SfidCodeAuth::CredentialNoncesByExpiry` (`max_values`: None, `max_size`: Some(6400024), added: 6402499, mode: `MaxEncodedLen`)
	/// Storage: `CitizenLightnodeIssuance::RewardClaimed` (r:1 w:1)
	/// Proof: `CitizenLightnodeIssuance::RewardClaimed` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenLightnodeIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenLightnodeIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenLightnodeIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenLightnodeIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bind_sfid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `237`
		//  Estimated: `6403489`
		// Minimum execution time: 142_425_000 picoseconds.
		Weight::from_parts(143_718_000, 0)
			.saturating_add(Weight::from_parts(0, 6403489))
			.saturating_add(T::DbWeight::get().reads(11))
			.saturating_add(T::DbWeight::get().writes(9))
	}
	/// Storage: `SfidCodeAuth::AccountToSfid` (r:1 w:1)
	/// Proof: `SfidCodeAuth::AccountToSfid` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::BoundCount` (r:1 w:1)
	/// Proof: `SfidCodeAuth::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidToAccount` (r:0 w:1)
	/// Proof: `SfidCodeAuth::SfidToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn unbind_sfid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308`
		//  Estimated: `3545`
		// Minimum execution time: 23_734_000 picoseconds.
		Weight::from_parts(24_515_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	/// Storage: `SfidCodeAuth::SfidMainAccount` (r:1 w:1)
	/// Proof: `SfidCodeAuth::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidBackupAccount1` (r:1 w:1)
	/// Proof: `SfidCodeAuth::SfidBackupAccount1` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidBackupAccount2` (r:1 w:1)
	/// Proof: `SfidCodeAuth::SfidBackupAccount2` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn rotate_sfid_keys() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `202`
		//  Estimated: `1517`
		// Minimum execution time: 20_368_000 picoseconds.
		Weight::from_parts(21_109_000, 0)
			.saturating_add(Weight::from_parts(0, 1517))
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

impl WeightInfo for () {
	/// Storage: `SfidCodeAuth::UsedCredentialNonce` (r:1 w:1)
	/// Proof: `SfidCodeAuth::UsedCredentialNonce` (`max_values`: None, `max_size`: Some(52), added: 2527, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidMainAccount` (r:1 w:0)
	/// Proof: `SfidCodeAuth::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `System::BlockHash` (r:1 w:0)
	/// Proof: `System::BlockHash` (`max_values`: None, `max_size`: Some(44), added: 2519, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidToAccount` (r:1 w:1)
	/// Proof: `SfidCodeAuth::SfidToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::AccountToSfid` (r:1 w:1)
	/// Proof: `SfidCodeAuth::AccountToSfid` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::BoundCount` (r:1 w:1)
	/// Proof: `SfidCodeAuth::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::CredentialNoncesByExpiry` (r:1 w:1)
	/// Proof: `SfidCodeAuth::CredentialNoncesByExpiry` (`max_values`: None, `max_size`: Some(6400024), added: 6402499, mode: `MaxEncodedLen`)
	/// Storage: `CitizenLightnodeIssuance::RewardClaimed` (r:1 w:1)
	/// Proof: `CitizenLightnodeIssuance::RewardClaimed` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenLightnodeIssuance::AccountRewarded` (r:1 w:1)
	/// Proof: `CitizenLightnodeIssuance::AccountRewarded` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `CitizenLightnodeIssuance::RewardedCount` (r:1 w:1)
	/// Proof: `CitizenLightnodeIssuance::RewardedCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	fn bind_sfid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `237`
		//  Estimated: `6403489`
		// Minimum execution time: 142_425_000 picoseconds.
		Weight::from_parts(143_718_000, 0)
			.saturating_add(Weight::from_parts(0, 6403489))
			.saturating_add(RocksDbWeight::get().reads(11))
			.saturating_add(RocksDbWeight::get().writes(9))
	}
	/// Storage: `SfidCodeAuth::AccountToSfid` (r:1 w:1)
	/// Proof: `SfidCodeAuth::AccountToSfid` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::BoundCount` (r:1 w:1)
	/// Proof: `SfidCodeAuth::BoundCount` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidToAccount` (r:0 w:1)
	/// Proof: `SfidCodeAuth::SfidToAccount` (`max_values`: None, `max_size`: Some(80), added: 2555, mode: `MaxEncodedLen`)
	fn unbind_sfid() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `308`
		//  Estimated: `3545`
		// Minimum execution time: 23_734_000 picoseconds.
		Weight::from_parts(24_515_000, 0)
			.saturating_add(Weight::from_parts(0, 3545))
			.saturating_add(RocksDbWeight::get().reads(2))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
	/// Storage: `SfidCodeAuth::SfidMainAccount` (r:1 w:1)
	/// Proof: `SfidCodeAuth::SfidMainAccount` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidBackupAccount1` (r:1 w:1)
	/// Proof: `SfidCodeAuth::SfidBackupAccount1` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	/// Storage: `SfidCodeAuth::SfidBackupAccount2` (r:1 w:1)
	/// Proof: `SfidCodeAuth::SfidBackupAccount2` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
	fn rotate_sfid_keys() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `202`
		//  Estimated: `1517`
		// Minimum execution time: 20_368_000 picoseconds.
		Weight::from_parts(21_109_000, 0)
			.saturating_add(Weight::from_parts(0, 1517))
			.saturating_add(RocksDbWeight::get().reads(3))
			.saturating_add(RocksDbWeight::get().writes(3))
	}
}
